appID: test-asyncwrapper
#pulsar properties
pulsar:
    pulsarURL : pulsar://localhost:6650
    orderTopic: new-order
    inputTopics :
        - input-topic1
        - input-topic2
        - input-topic3
    outputTopic : output-topic
    failureTopic: failure-topic
#wps properties
wps:
    wpsURL : https://rz-vm140.gfz-potsdam.de/wps/WebProcessingService
    version : 2.0.0
    process : org.n52.wps.server.algorithm.test.EchoProcess
